#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Optimizations."""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6720b61a367'
down_revision = '26845fffb502'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxonomy', sa.Column('root_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_taxonomy_root_id_taxonomy_term'), 'taxonomy', 'taxonomy_term', ['root_id'], ['id'])
    op.create_unique_constraint(op.f('uq_taxonomy_term_slug'), 'taxonomy_term', ['slug', 'tree_id'])
    op.drop_constraint('fk_taxonomy_term_taxonomy_id_taxonomy', 'taxonomy_term', type_='foreignkey')
    op.drop_column('taxonomy_term', 'taxonomy_id')
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxonomy_term', sa.Column('taxonomy_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('fk_taxonomy_term_taxonomy_id_taxonomy', 'taxonomy_term', 'taxonomy', ['taxonomy_id'], ['id'])
    op.drop_constraint(op.f('uq_taxonomy_term_slug'), 'taxonomy_term', type_='unique')
    op.drop_constraint(op.f('fk_taxonomy_root_id_taxonomy_term'), 'taxonomy', type_='foreignkey')
    op.drop_column('taxonomy', 'root_id')
    # ### end Alembic commands ###
